github.event.inputs => inputs

diff --git a/.github/workflows/build-dask-eopf.yml b/.github/workflows/build-dask-eopf.yml
--- a/.github/workflows/build-dask-eopf.yml
+++ b/.github/workflows/build-dask-eopf.yml
@@ -50,8 +50,8 @@ on:
       - '.github/workflows/build-dask-eopf.yml'
   workflow_dispatch: # manual trigger
     inputs:
-      docker_tag:
-        description: Tag the docker images as e.g. 'latest' or 'feat-rspy123'
+      add_docker_tags:
+        description: Add these tags to the docker images as e.g. 'custom-tag1,custom-tag-2'
         required: false
       processor:
         description: Which processor to build an image for
@@ -68,12 +68,8 @@ on:
           - mockup
       build_base_images:
         description: Build the base image before building the Dask images?
-        required: false
-        default: 'true'
-        type: choice
-        options:
-          - 'true'
-          - 'false'
+        type: boolean
+        default: true
       target_system:
         description: Whether to build images for cluster deployment, local deployment, LocalCluster mode or all of them
         required: false
@@ -98,7 +94,8 @@ jobs:
     permissions:
       pull-requests: read
     outputs:
-      # Note: we tie "base" and "common" outputs to the manual trigger as well, to trigger all the image builds anytime the workflow is triggered manually.
+      # Note: we tie "base" and "common" outputs to the manual trigger as well,
+      # to trigger all the image builds anytime the workflow is triggered manually.
       base: ${{ steps.filter.outputs.base }}
       common: ${{ steps.filter.outputs.common }}
       cpm2: ${{ steps.filter.outputs.cpm2 }}
@@ -106,6 +103,7 @@ jobs:
       l0: ${{ steps.filter.outputs.l0 }}
       s1ard: ${{ steps.filter.outputs.s1ard }}
       s3olci: ${{ steps.filter.outputs.s3olci }}
+      any_changes: ${{ steps.any_changes.outputs.value }}
     steps:
       - uses: actions/checkout@v6
       - uses: dorny/paths-filter@v4
@@ -129,13 +127,50 @@ jobs:
             s1ard: ['docker/**/*dask-s1ard.*']
             s3olci: ['docker/**/*dask-s3olci.*']
           list-files: 'json' # Enables listing of files matching the filter
+      - id: any_changes
+        name: Any changes ?
+        run: |
+          set -x
+          # Do we have any changes in the processor files ?
+          any_changes=false
+          if [[ \
+            (${{ steps.filter.outputs.base }} == 'true') || \
+            (${{ steps.filter.outputs.common }} == 'true') || \
+            (${{ steps.filter.outputs.cpm2 }} == 'true') || \
+            (${{ steps.filter.outputs.cpm3 }} == 'true') || \
+            (${{ steps.filter.outputs.l0 }} == 'true') || \
+            (${{ steps.filter.outputs.s1ard }} == 'true') || \
+            (${{ steps.filter.outputs.s3olci }} == 'true') \
+          ]]; then
+            any_changes=true
+          fi
+          echo "value=$any_changes" >> $GITHUB_OUTPUT
+        shell: bash
+
+  set-binary-env:
+    name: Set Docker environment
+    if: github.actor != 'dependabot[bot]'
+    runs-on: ubuntu-latest
+    outputs:
+      branch_name: ${{ steps.set-binary-env.outputs.branch_name }}
+      # Use directly the final tags
+      docker_tags: ${{ steps.set-binary-env.outputs.docker_tags }},${{ steps.set-binary-env.outputs.docker_final_tags }}
+    steps:
+      - id: set-binary-env
+        name: Call action 'set-binary-env'
+        uses: RS-PYTHON/actions/.github/actions/set-binary-env@feat-rspy1108/jupyter-cicd
+        with:
+          add_docker_tags: ${{ inputs.add_docker_tags }}
 
   # Build base images for Dask only
   build-base-dask-images:
     runs-on: ubuntu-latest
     name: Build base images for Dask
     needs: [changes]
-    if: ${{ (needs.changes.outputs.base == 'true') || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.build_base_images == 'true')) }}
+    if: ${{
+      (needs.changes.outputs.base == 'true') ||
+      ((github.event_name == 'workflow_dispatch') && (inputs.build_base_images == true))
+      }}
     permissions:
       contents: read
       packages: write
@@ -147,60 +182,19 @@ jobs:
       - name: Build and push base images
         run: docker/base/build-base-images.sh -t dask --push
 
-  # Calculate variables for this workflow
-  set-env:
-    runs-on: ubuntu-latest
-    name: Set environment
-    needs: [changes]
-    outputs:
-      branch_name: ${{ steps.set-binary-env.outputs.branch_name }}
-      docker_tags: ${{ case(
-        steps.set-binary-env.outputs.docker_final_tags != '',
-        steps.set-binary-env.outputs.docker_final_tags,
-        steps.set-binary-env.outputs.docker_tags) }} # don't use temp tags, take directly the final tags
-      common_changes: ${{ steps.other-env.outputs.common_changes }}
-      any_changes: ${{ steps.other-env.outputs.any_changes }}
-    steps:
-      - id: set-binary-env
-        name: Call action 'set-binary-env'
-        uses: RS-PYTHON/actions/.github/actions/set-binary-env@develop
-        with:
-          manual_tag: ${{ github.event.inputs.docker_tag }}
-      - id: other-env
-        name: Set environment
-        run: |
-          set -x
-
-          # We always trigger the image builds if the common files have changed
-          common_changes=${{ needs.changes.outputs.common }}
-
-          # Do we have any changes in the processor files or was the job triggered manually ?
-          any_changes=false
-          if [[ \
-            (${common_changes} == 'true') || \
-            (${{ needs.changes.outputs.base }} == 'true') || \
-            (${{ needs.changes.outputs.l0 }} == 'true') || \
-            (${{ needs.changes.outputs.s1ard }} == 'true') || \
-            (${{ needs.changes.outputs.s3olci }} == 'true') \
-          ]]; then
-            any_changes=true
-          fi
-
-          # Save values
-          echo "common_changes=$common_changes" >> $GITHUB_OUTPUT
-          echo "any_changes=$any_changes" >> $GITHUB_OUTPUT
-        shell: bash
-
   build-dask-eopf:
     runs-on: ubuntu-latest
     name: Build images for processor
-    needs: [changes, set-env, build-base-dask-images]
+    needs: [changes, set-binary-env, build-base-dask-images]
     # Job run when there are changes OR a manual trigger, EVEN if any previous job is skipped
-    if: ${{ always() && !failure() && !cancelled() && ((needs.set-env.outputs.any_changes == 'true') || (github.event_name == 'workflow_dispatch')) }}
+    if: ${{
+      always() && !failure() && !cancelled() &&
+      ((needs.changes.outputs.any_changes == 'true') || (github.event_name == 'workflow_dispatch'))
+      }}
     permissions:
       packages: write
     env:
-      DOCKER_TAGS: ${{ needs.set-env.outputs.docker_tags }}
+      DOCKER_TAGS: ${{ needs.set-binary-env.outputs.docker_tags }}
 
     # See: https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations
     strategy:
@@ -210,21 +204,63 @@ jobs:
         target: [cluster, local, localcluster] # No option = main image for cluster deployment, "local" is for local deployment and "localcluster" is for local debugging
         include:
           - proc: cpm2
-            proccondition: "${{ (needs.changes.outputs.cpm2 == 'true') || (needs.set-env.outputs.common_changes == 'true') || (needs.changes.outputs.base == 'true') || ((github.event_name == 'workflow_dispatch') && ((github.event.inputs.processor == 'cpm2') || (github.event.inputs.processor == 'all'))) }}"
+            proccondition: ${{
+              (needs.changes.outputs.cpm2 == 'true') ||
+              (needs.changes.outputs.common == 'true') ||
+              (needs.changes.outputs.base == 'true') ||
+              ((github.event_name == 'workflow_dispatch') &&
+                ((inputs.processor == 'cpm2') || (inputs.processor == 'all')))
+              }}
           - proc: cpm3
-            proccondition: "${{ (needs.changes.outputs.cpm3 == 'true') || (needs.set-env.outputs.common_changes == 'true') || (needs.changes.outputs.base == 'true') || ((github.event_name == 'workflow_dispatch') && ((github.event.inputs.processor == 'cpm3') || (github.event.inputs.processor == 'all'))) }}"
+            proccondition: ${{
+              (needs.changes.outputs.cpm3 == 'true') ||
+              (needs.changes.outputs.common == 'true') ||
+              (needs.changes.outputs.base == 'true') ||
+              ((github.event_name == 'workflow_dispatch') &&
+                ((inputs.processor == 'cpm3') || (inputs.processor == 'all')))
+              }}
           - proc: l0
-            proccondition: "${{ (needs.changes.outputs.l0 == 'true') || (needs.set-env.outputs.common_changes == 'true') || (needs.changes.outputs.base == 'true') || ((github.event_name == 'workflow_dispatch') && ((github.event.inputs.processor == 'l0') || (github.event.inputs.processor == 'all'))) }}"
+            proccondition: ${{
+              (needs.changes.outputs.l0 == 'true') ||
+              (needs.changes.outputs.common == 'true') ||
+              (needs.changes.outputs.base == 'true') ||
+              ((github.event_name == 'workflow_dispatch') &&
+                ((inputs.processor == 'l0') || (inputs.processor == 'all')))
+              }}
           - proc: s1ard
-            proccondition: "${{ (needs.changes.outputs.s1ard == 'true') || (needs.set-env.outputs.common_changes == 'true') || (needs.changes.outputs.base == 'true') || ((github.event_name == 'workflow_dispatch') && ((github.event.inputs.processor == 's1ard') || (github.event.inputs.processor == 'all'))) }}"
+            proccondition: ${{
+              (needs.changes.outputs.s1ard == 'true') ||
+              (needs.changes.outputs.common == 'true') ||
+              (needs.changes.outputs.base == 'true') ||
+              ((github.event_name == 'workflow_dispatch') &&
+                ((inputs.processor == 's1ard') || (inputs.processor == 'all')))
+              }}
           - proc: s3olci
-            proccondition: "${{ (needs.changes.outputs.s3olci == 'true') || (needs.set-env.outputs.common_changes == 'true') || (needs.changes.outputs.base == 'true') || ((github.event_name == 'workflow_dispatch') && ((github.event.inputs.processor == 's3olci') || (github.event.inputs.processor == 'all'))) }}"
+            proccondition: ${{
+              (needs.changes.outputs.s3olci == 'true') ||
+              (needs.changes.outputs.common == 'true') ||
+              (needs.changes.outputs.base == 'true') ||
+              ((github.event_name == 'workflow_dispatch') &&
+                ((inputs.processor == 's3olci') || (inputs.processor == 'all')))
+              }}
           - target: cluster
-            targetcondition: "${{ (github.event_name != 'workflow_dispatch') || (github.event.inputs.target_system == 'cluster') || (github.event.inputs.target_system == 'all') }}"
+            targetcondition: ${{
+              (github.event_name != 'workflow_dispatch') ||
+              (inputs.target_system == 'cluster') ||
+              (inputs.target_system == 'all')
+              }}
           - target: local
-            targetcondition: "${{ (github.event_name != 'workflow_dispatch') || ( github.event.inputs.target_system == 'local') || (github.event.inputs.target_system == 'all') }}"
+            targetcondition: ${{
+              (github.event_name != 'workflow_dispatch') ||
+              (inputs.target_system == 'local') ||
+              (inputs.target_system == 'all')
+              }}
           - target: localcluster
-            targetcondition: "${{ (github.event_name != 'workflow_dispatch') || ( github.event.inputs.target_system == 'localcluster') || (github.event.inputs.target_system == 'all') }}"
+            targetcondition: ${{
+              (github.event_name != 'workflow_dispatch') ||
+              (inputs.target_system == 'localcluster') ||
+              (inputs.target_system == 'all')
+              }}
 
     steps:
       - name: Display build info
@@ -235,19 +271,19 @@ jobs:
         shell: bash
 
       - name: Checkout
-        if: matrix.proccondition && matrix.targetcondition
+        if: ${{ matrix.proccondition && matrix.targetcondition }}
         uses: actions/checkout@v6
 
       # Login to Docker Hub to increase pull quota from 100 to 200 per 6 hours
       - name: Log into Docker Hub
-        if: matrix.proccondition && matrix.targetcondition
+        if: ${{ matrix.proccondition && matrix.targetcondition }}
         uses: docker/login-action@v3
         with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Log into GitHub Container Registry
-        if: matrix.proccondition && matrix.targetcondition
+        if: ${{ matrix.proccondition && matrix.targetcondition }}
         uses: docker/login-action@v3
         with:
           registry: ${{ env.DOCKER_REGISTRY }}
@@ -257,14 +293,14 @@ jobs:
       # Extract metadata from Git reference and GitHub events
       - name: Extract Docker metadata
         id: meta
-        if: matrix.proccondition && matrix.targetcondition
+        if: ${{ matrix.proccondition && matrix.targetcondition }}
         uses: docker/metadata-action@v5
         with:
           images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }} # ghcr.io/RS-PYTHON/rs-workflow-env
 
       - id: build
         name: Build the Dask images
-        if: matrix.proccondition && matrix.targetcondition
+        if: ${{ matrix.proccondition && matrix.targetcondition }}
         run: |
           set -x
 
@@ -294,7 +330,7 @@ jobs:
         shell: bash
 
       - name: Run Trivy vulnerability scanner
-        if: matrix.proccondition && matrix.targetcondition
+        if: ${{ matrix.proccondition && matrix.targetcondition }}
         uses: aquasecurity/trivy-action@master
         env:
           TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
@@ -310,14 +346,14 @@ jobs:
           #timeout: '30m'
 
       - name: Upload Trivy scan results to GitHub Security tab
-        if: matrix.proccondition && matrix.targetcondition
+        if: ${{ matrix.proccondition && matrix.targetcondition }}
         uses: github/codeql-action/upload-sarif@v4
         with:
           sarif_file: trivy-results-docker.sarif
           category: ${{ steps.build.outputs.repository }}
 
       - name: Display link to Trivy results
-        if: matrix.proccondition && matrix.targetcondition
+        if: ${{ matrix.proccondition && matrix.targetcondition }}
         run: |
 
             set -x
@@ -337,7 +373,7 @@ jobs:
         shell: bash
 
       - name: Push Docker image
-        if: matrix.proccondition && matrix.targetcondition
+        if: ${{ matrix.proccondition && matrix.targetcondition }}
         run: |
           set -x
           for tag in ${DOCKER_TAGS//,/ }; do
@@ -345,27 +381,32 @@ jobs:
           done
         shell: bash
 
-  trigger-dask-mockup-images-build:
-    runs-on: ubuntu-latest
-    name: Trigger rs-testmeans CI to build the Dask mockup image
-    needs: [changes, set-env, build-base-dask-images]
-    # Trigger CI for mockup images only if base images are changed OR if asked by manual trigger
-    if: ${{ always() && !failure() && !cancelled() && ((needs.changes.outputs.base == 'true') || ((github.event_name == 'workflow_dispatch') && ((github.event.inputs.processor == 'mockup') || (github.event.inputs.processor == 'all')))) }}
-    steps:
-      - env:
-          DOCKER_TAGS: ${{ needs.set-env.outputs.docker_tags }}
-          TRIGGER_WORKFLOWS_TOKEN: ${{ secrets.TRIGGER_WORKFLOWS }}
-        run: |
-          set -x
+  # trigger-dask-mockup-images-build:
+  #   runs-on: ubuntu-latest
+  #   name: Trigger rs-testmeans CI to build the Dask mockup image
+  #   needs: [changes, set-binary-env, build-base-dask-images]
+  #   # Trigger CI for mockup images only if base images are changed OR if asked by manual trigger
+  #   if: ${{
+  #     always() && !failure() && !cancelled() &&
+  #     ((needs.changes.outputs.base == 'true') ||
+  #       ((github.event_name == 'workflow_dispatch') &&
+  #         ((inputs.processor == 'mockup') || (inputs.processor == 'all'))))
+  #     }}
+  #   steps:
+  #     - env:
+  #         DOCKER_TAGS: ${{ needs.set-env.outputs.docker_tags }}
+  #         TRIGGER_WORKFLOWS_TOKEN: ${{ secrets.TRIGGER_WORKFLOWS }}
+  #       run: |
+  #         set -x
 
-          # Keep last tag (after the last ',')
-          docker_tag=${DOCKER_TAGS##*,}
+  #         # Keep last tag (after the last ',')
+  #         docker_tag=${DOCKER_TAGS##*,}
 
-          curl -L \
-            -X POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${TRIGGER_WORKFLOWS_TOKEN}" \
-            -H "X-GitHub-Api-Version: 2026-03-10" \
-            https://api.github.com/repos/RS-PYTHON/rs-testmeans/actions/workflows/publish-binaries.yml/dispatches \
-            -d '{"ref":"${{ needs.set-env.outputs.branch_name }}","inputs":{"docker_tag":"'"$docker_tag"'","build_only_mockup_images":"true"}}'
-        shell: bash
+  #         curl -L \
+  #           -X POST \
+  #           -H "Accept: application/vnd.github+json" \
+  #           -H "Authorization: Bearer ${TRIGGER_WORKFLOWS_TOKEN}" \
+  #           -H "X-GitHub-Api-Version: 2026-03-10" \
+  #           https://api.github.com/repos/RS-PYTHON/rs-testmeans/actions/workflows/publish-binaries.yml/dispatches \
+  #           -d '{"ref":"${{ needs.set-env.outputs.branch_name }}","inputs":{"docker_tag":"'"$docker_tag"'","build_only_mockup_images":"true"}}'
+  #       shell: bash
